/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author anhha
 */
public class Trang extends javax.swing.JFrame {

    /**
     * Creates new form Trang
     */
    public Trang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        txtMenu = new javax.swing.JLabel();
        txtHoaDon = new javax.swing.JLabel();
        txtNhanVien = new javax.swing.JLabel();
        txtKhachHang = new javax.swing.JLabel();
        txtIconAd = new javax.swing.JLabel();
        txtUuDai = new javax.swing.JLabel();
        sprt2 = new javax.swing.JSeparator();
        txtDanhGia = new javax.swing.JLabel();
        txtAdmin = new javax.swing.JLabel();
        txtDichVu = new javax.swing.JLabel();
        txtTrangChu = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JLabel();
        txtBan = new javax.swing.JLabel();
        sprt3 = new javax.swing.JSeparator();
        txtDoiMatKhau = new javax.swing.JLabel();
        txtDangXuat = new javax.swing.JLabel();
        pnContainer = new javax.swing.JPanel();
        pnTrangChu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnTaiKhoan = new javax.swing.JPanel();
        pnListTaiKhoan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTaiKhoan = new javax.swing.JTable();
        pnFormTaiKhoan = new javax.swing.JPanel();
        btSuaTaiKhoan = new javax.swing.JButton();
        btThemTaiKhoan = new javax.swing.JButton();
        btXoaTaiKhoan = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        btTimKiemTaiKhoan = new javax.swing.JButton();
        pnBan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnThucDon = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnHoaDon = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnNhanVien = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnFormNhanVien = new javax.swing.JPanel();
        btSuaNhanVien = new javax.swing.JButton();
        btThemNhanVien = new javax.swing.JButton();
        btXoaNhanVien = new javax.swing.JButton();
        btResetNhanVien = new javax.swing.JButton();
        txtHoTenNhanVien = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtEmailNhanVien = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDiaChiNhanVien = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btGioiTinhNam = new javax.swing.JRadioButton();
        btGioiTinhNu = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        txtSdtNhanVien = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNgaySinhNhanVien = new javax.swing.JTextField();
        txtTrangThai = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        txtTrangThai1 = new javax.swing.JLabel();
        txtNgaySinhNhanVien1 = new javax.swing.JTextField();
        pnListNhanVien = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        pnKhachHang = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnUuDai = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnDanhGia = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnDichVu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lí");
        setPreferredSize(new java.awt.Dimension(1000, 650));

        pnMain.setBackground(new java.awt.Color(255, 255, 255));

        pnMenu.setBackground(new java.awt.Color(255, 153, 102));
        pnMenu.setPreferredSize(new java.awt.Dimension(170, 600));

        txtTitle.setBackground(new java.awt.Color(255, 255, 255));
        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(102, 51, 0));
        txtTitle.setText("DOOKKI");

        txtMenu.setForeground(new java.awt.Color(255, 255, 255));
        txtMenu.setText("Menu");
        txtMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMenuMouseClicked(evt);
            }
        });

        txtHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        txtHoaDon.setText("Hóa Đơn");
        txtHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHoaDonMouseClicked(evt);
            }
        });

        txtNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        txtNhanVien.setText("Nhân Viên");
        txtNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNhanVienMouseClicked(evt);
            }
        });

        txtKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        txtKhachHang.setText("Khách Hàng");
        txtKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKhachHangMouseClicked(evt);
            }
        });

        txtIconAd.setForeground(new java.awt.Color(255, 255, 255));
        txtIconAd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/administrator (1).png"))); // NOI18N

        txtUuDai.setForeground(new java.awt.Color(255, 255, 255));
        txtUuDai.setText("Ưu Đãi");
        txtUuDai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUuDaiMouseClicked(evt);
            }
        });

        sprt2.setBackground(new java.awt.Color(255, 255, 255));
        sprt2.setForeground(new java.awt.Color(255, 255, 255));

        txtDanhGia.setForeground(new java.awt.Color(255, 255, 255));
        txtDanhGia.setText("Đánh Giá");
        txtDanhGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDanhGiaMouseClicked(evt);
            }
        });

        txtAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAdmin.setForeground(new java.awt.Color(255, 255, 255));
        txtAdmin.setText("Admin");

        txtDichVu.setForeground(new java.awt.Color(255, 255, 255));
        txtDichVu.setText("Dịch Vụ");
        txtDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDichVuMouseClicked(evt);
            }
        });

        txtTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        txtTrangChu.setText("Trang Chủ");
        txtTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTrangChuMouseClicked(evt);
            }
        });

        txtTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        txtTaiKhoan.setText("Tài Khoản");
        txtTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTaiKhoanMouseClicked(evt);
            }
        });

        txtBan.setForeground(new java.awt.Color(255, 255, 255));
        txtBan.setText("Bàn");
        txtBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBanMouseClicked(evt);
            }
        });

        txtDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtDoiMatKhau.setForeground(new java.awt.Color(0, 102, 255));
        txtDoiMatKhau.setText("Đổi Mật Khẩu");

        txtDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtDangXuat.setForeground(new java.awt.Color(255, 0, 0));
        txtDangXuat.setText("Đăng Xuất");

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sprt2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sprt3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txtIconAd))
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(txtAdmin))
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTaiKhoan)
                            .addComponent(txtTrangChu)
                            .addComponent(txtBan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMenu)
                            .addComponent(txtHoaDon)
                            .addComponent(txtNhanVien)
                            .addComponent(txtKhachHang)
                            .addComponent(txtUuDai)
                            .addComponent(txtDanhGia)
                            .addComponent(txtDichVu)))
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDoiMatKhau)
                            .addGroup(pnMenuLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtDangXuat))))
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtTitle)))
                .addGap(40, 44, Short.MAX_VALUE))
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIconAd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprt2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTrangChu)
                .addGap(18, 18, 18)
                .addComponent(txtTaiKhoan)
                .addGap(18, 18, 18)
                .addComponent(txtBan)
                .addGap(18, 18, 18)
                .addComponent(txtMenu)
                .addGap(18, 18, 18)
                .addComponent(txtHoaDon)
                .addGap(18, 18, 18)
                .addComponent(txtNhanVien)
                .addGap(18, 18, 18)
                .addComponent(txtKhachHang)
                .addGap(18, 18, 18)
                .addComponent(txtUuDai)
                .addGap(18, 18, 18)
                .addComponent(txtDanhGia)
                .addGap(18, 18, 18)
                .addComponent(txtDichVu)
                .addGap(29, 29, 29)
                .addComponent(sprt3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDoiMatKhau)
                .addGap(12, 12, 12)
                .addComponent(txtDangXuat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnContainer.setLayout(new java.awt.CardLayout());

        pnTrangChu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Trang Chủ");

        javax.swing.GroupLayout pnTrangChuLayout = new javax.swing.GroupLayout(pnTrangChu);
        pnTrangChu.setLayout(pnTrangChuLayout);
        pnTrangChuLayout.setHorizontalGroup(
            pnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTrangChuLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addContainerGap(570, Short.MAX_VALUE))
        );
        pnTrangChuLayout.setVerticalGroup(
            pnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTrangChuLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addContainerGap(587, Short.MAX_VALUE))
        );

        pnContainer.add(pnTrangChu, "card3");

        pnTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));

        pnListTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        pnListTaiKhoan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách tài khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tài Khoản", "Tên Tài Khoản", "MK Tài Khoản"
            }
        ));
        jScrollPane1.setViewportView(tbTaiKhoan);

        javax.swing.GroupLayout pnListTaiKhoanLayout = new javax.swing.GroupLayout(pnListTaiKhoan);
        pnListTaiKhoan.setLayout(pnListTaiKhoanLayout);
        pnListTaiKhoanLayout.setHorizontalGroup(
            pnListTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        pnListTaiKhoanLayout.setVerticalGroup(
            pnListTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
        );

        pnFormTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        pnFormTaiKhoan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Tài Khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnFormTaiKhoan.setToolTipText("");

        btSuaTaiKhoan.setBackground(new java.awt.Color(255, 102, 0));
        btSuaTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btSuaTaiKhoan.setText("Sửa");
        btSuaTaiKhoan.setMaximumSize(new java.awt.Dimension(72, 72));
        btSuaTaiKhoan.setMinimumSize(new java.awt.Dimension(72, 72));

        btThemTaiKhoan.setBackground(new java.awt.Color(255, 102, 0));
        btThemTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btThemTaiKhoan.setText("Thêm");
        btThemTaiKhoan.setMaximumSize(new java.awt.Dimension(72, 72));
        btThemTaiKhoan.setMinimumSize(new java.awt.Dimension(72, 72));

        btXoaTaiKhoan.setBackground(new java.awt.Color(255, 102, 0));
        btXoaTaiKhoan.setForeground(new java.awt.Color(242, 242, 242));
        btXoaTaiKhoan.setText("Xóa");
        btXoaTaiKhoan.setMaximumSize(new java.awt.Dimension(72, 72));
        btXoaTaiKhoan.setMinimumSize(new java.awt.Dimension(72, 72));

        btReset.setBackground(new java.awt.Color(255, 102, 0));
        btReset.setForeground(new java.awt.Color(255, 255, 255));
        btReset.setText("Reset");
        btReset.setMaximumSize(new java.awt.Dimension(72, 72));
        btReset.setMinimumSize(new java.awt.Dimension(72, 72));

        jLabel11.setText("Mã tài khoản");

        jLabel12.setText("Tên tài khoản");

        jLabel13.setText("Mật khẩu");

        javax.swing.GroupLayout pnFormTaiKhoanLayout = new javax.swing.GroupLayout(pnFormTaiKhoan);
        pnFormTaiKhoan.setLayout(pnFormTaiKhoanLayout);
        pnFormTaiKhoanLayout.setHorizontalGroup(
            pnFormTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormTaiKhoanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnFormTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnFormTaiKhoanLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnFormTaiKhoanLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2))
                    .addGroup(pnFormTaiKhoanLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(40, 40, 40)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addGroup(pnFormTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btReset, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addGroup(pnFormTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btThemTaiKhoan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addComponent(btSuaTaiKhoan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btXoaTaiKhoan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        pnFormTaiKhoanLayout.setVerticalGroup(
            pnFormTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormTaiKhoanLayout.createSequentialGroup()
                .addGroup(pnFormTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormTaiKhoanLayout.createSequentialGroup()
                        .addComponent(btThemTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSuaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btXoaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnFormTaiKhoanLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnFormTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnFormTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnFormTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("Quản Lí Tài Khoản");

        btTimKiemTaiKhoan.setText("Tìm Kiếm");

        javax.swing.GroupLayout pnTaiKhoanLayout = new javax.swing.GroupLayout(pnTaiKhoan);
        pnTaiKhoan.setLayout(pnTaiKhoanLayout);
        pnTaiKhoanLayout.setHorizontalGroup(
            pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnFormTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnListTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTaiKhoanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btTimKiemTaiKhoan)
                .addGap(46, 46, 46))
        );
        pnTaiKhoanLayout.setVerticalGroup(
            pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnFormTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTimKiemTaiKhoan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnListTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnContainer.add(pnTaiKhoan, "card2");

        pnBan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Bàn");

        javax.swing.GroupLayout pnBanLayout = new javax.swing.GroupLayout(pnBan);
        pnBan.setLayout(pnBanLayout);
        pnBanLayout.setHorizontalGroup(
            pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBanLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel2)
                .addContainerGap(580, Short.MAX_VALUE))
        );
        pnBanLayout.setVerticalGroup(
            pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBanLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel2)
                .addContainerGap(456, Short.MAX_VALUE))
        );

        pnContainer.add(pnBan, "card4");

        pnThucDon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Thwujc dơn");

        javax.swing.GroupLayout pnThucDonLayout = new javax.swing.GroupLayout(pnThucDon);
        pnThucDon.setLayout(pnThucDonLayout);
        pnThucDonLayout.setHorizontalGroup(
            pnThucDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThucDonLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel3)
                .addContainerGap(508, Short.MAX_VALUE))
        );
        pnThucDonLayout.setVerticalGroup(
            pnThucDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThucDonLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel3)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        pnContainer.add(pnThucDon, "card5");

        pnHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Hóa Đơn");

        javax.swing.GroupLayout pnHoaDonLayout = new javax.swing.GroupLayout(pnHoaDon);
        pnHoaDon.setLayout(pnHoaDonLayout);
        pnHoaDonLayout.setHorizontalGroup(
            pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHoaDonLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel4)
                .addContainerGap(521, Short.MAX_VALUE))
        );
        pnHoaDonLayout.setVerticalGroup(
            pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHoaDonLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel4)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        pnContainer.add(pnHoaDon, "card6");

        pnNhanVien.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 51));
        jLabel6.setText("Quản Lí Nhân Viên");

        pnFormNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Tài Khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnFormNhanVien.setToolTipText("");

        btSuaNhanVien.setBackground(new java.awt.Color(255, 102, 0));
        btSuaNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btSuaNhanVien.setText("Sửa");

        btThemNhanVien.setBackground(new java.awt.Color(255, 102, 0));
        btThemNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btThemNhanVien.setText("Thêm");

        btXoaNhanVien.setBackground(new java.awt.Color(255, 102, 0));
        btXoaNhanVien.setForeground(new java.awt.Color(242, 242, 242));
        btXoaNhanVien.setText("Xóa");

        btResetNhanVien.setBackground(new java.awt.Color(255, 102, 0));
        btResetNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btResetNhanVien.setText("Reset");

        jLabel14.setText("Họ Tên");

        jLabel15.setText("Email");

        jLabel16.setText("Địa chỉ");

        jLabel17.setText("Giới tính");

        btGioiTinhNam.setText("Nam");

        btGioiTinhNu.setText("Nữ");

        jLabel18.setText("SĐT");

        jLabel19.setText("Ngày sinh");

        txtTrangThai.setText("Trạng thái");

        jRadioButton3.setText("jRadioButton3");

        jRadioButton4.setText("jRadioButton4");

        txtTrangThai1.setText("Ghi Chú");

        javax.swing.GroupLayout pnFormNhanVienLayout = new javax.swing.GroupLayout(pnFormNhanVien);
        pnFormNhanVien.setLayout(pnFormNhanVienLayout);
        pnFormNhanVienLayout.setHorizontalGroup(
            pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormNhanVienLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormNhanVienLayout.createSequentialGroup()
                        .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmailNhanVien, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChiNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(txtHoTenNhanVien)))
                    .addGroup(pnFormNhanVienLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btGioiTinhNam)
                        .addGap(18, 18, 18)
                        .addComponent(btGioiTinhNu)))
                .addGap(53, 53, 53)
                .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormNhanVienLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSdtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnFormNhanVienLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgaySinhNhanVien))
                    .addGroup(pnFormNhanVienLayout.createSequentialGroup()
                        .addComponent(txtTrangThai1)
                        .addGap(24, 24, 24)
                        .addComponent(txtNgaySinhNhanVien1))
                    .addGroup(pnFormNhanVienLayout.createSequentialGroup()
                        .addComponent(txtTrangThai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4)))
                .addGap(81, 81, 81)
                .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSuaNhanVien)
                    .addComponent(btThemNhanVien)
                    .addComponent(btXoaNhanVien)
                    .addComponent(btResetNhanVien))
                .addGap(29, 29, 29))
        );
        pnFormNhanVienLayout.setVerticalGroup(
            pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormNhanVienLayout.createSequentialGroup()
                .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormNhanVienLayout.createSequentialGroup()
                        .addComponent(btThemNhanVien)
                        .addGap(18, 18, 18)
                        .addComponent(btSuaNhanVien)
                        .addGap(18, 18, 18)
                        .addComponent(btXoaNhanVien))
                    .addGroup(pnFormNhanVienLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtHoTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(txtSdtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtEmailNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtNgaySinhNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtDiaChiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrangThai)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))))
                .addGap(18, 18, 18)
                .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(btGioiTinhNam)
                        .addComponent(btGioiTinhNu)
                        .addComponent(btResetNhanVien))
                    .addGroup(pnFormNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTrangThai1)
                        .addComponent(txtNgaySinhNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnListNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Email", "Địa chỉ", "Giới tính", "SĐT", "Ngày sinh", "Trạng thái", "Ghi chú"
            }
        ));
        jScrollPane2.setViewportView(tbNhanVien);

        javax.swing.GroupLayout pnListNhanVienLayout = new javax.swing.GroupLayout(pnListNhanVien);
        pnListNhanVien.setLayout(pnListNhanVienLayout);
        pnListNhanVienLayout.setHorizontalGroup(
            pnListNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListNhanVienLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0))
        );
        pnListNhanVienLayout.setVerticalGroup(
            pnListNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnNhanVienLayout = new javax.swing.GroupLayout(pnNhanVien);
        pnNhanVien.setLayout(pnNhanVienLayout);
        pnNhanVienLayout.setHorizontalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFormNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnListNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnNhanVienLayout.setVerticalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnFormNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(pnListNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnContainer.add(pnNhanVien, "card7");

        pnKhachHang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Khách hàng");

        javax.swing.GroupLayout pnKhachHangLayout = new javax.swing.GroupLayout(pnKhachHang);
        pnKhachHang.setLayout(pnKhachHangLayout);
        pnKhachHangLayout.setHorizontalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel7)
                .addContainerGap(508, Short.MAX_VALUE))
        );
        pnKhachHangLayout.setVerticalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel7)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        pnContainer.add(pnKhachHang, "card8");

        pnUuDai.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Ưu đãi");

        javax.swing.GroupLayout pnUuDaiLayout = new javax.swing.GroupLayout(pnUuDai);
        pnUuDai.setLayout(pnUuDaiLayout);
        pnUuDaiLayout.setHorizontalGroup(
            pnUuDaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUuDaiLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel8)
                .addContainerGap(534, Short.MAX_VALUE))
        );
        pnUuDaiLayout.setVerticalGroup(
            pnUuDaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUuDaiLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel8)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        pnContainer.add(pnUuDai, "card9");

        pnDanhGia.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Đánh giá");

        javax.swing.GroupLayout pnDanhGiaLayout = new javax.swing.GroupLayout(pnDanhGia);
        pnDanhGia.setLayout(pnDanhGiaLayout);
        pnDanhGiaLayout.setHorizontalGroup(
            pnDanhGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDanhGiaLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel9)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        pnDanhGiaLayout.setVerticalGroup(
            pnDanhGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDanhGiaLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel9)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        pnContainer.add(pnDanhGia, "card10");

        pnDichVu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Dịch vụ");

        javax.swing.GroupLayout pnDichVuLayout = new javax.swing.GroupLayout(pnDichVu);
        pnDichVu.setLayout(pnDichVuLayout);
        pnDichVuLayout.setHorizontalGroup(
            pnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDichVuLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel10)
                .addContainerGap(530, Short.MAX_VALUE))
        );
        pnDichVuLayout.setVerticalGroup(
            pnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDichVuLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel10)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        pnContainer.add(pnDichVu, "card11");

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTrangChuMouseClicked
        pnTrangChu.setVisible(true);
        pnTaiKhoan.setVisible(false);
        pnBan.setVisible(false);
        pnThucDon.setVisible(false);
        pnHoaDon.setVisible(false);
        pnNhanVien.setVisible(false);
        pnKhachHang.setVisible(false);
        pnUuDai.setVisible(false);
        pnDanhGia.setVisible(false);
        pnDichVu.setVisible(false);

    }//GEN-LAST:event_txtTrangChuMouseClicked

    private void txtTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTaiKhoanMouseClicked
        pnTaiKhoan.setVisible(true);
        pnTrangChu.setVisible(false);
        pnBan.setVisible(false);
        pnThucDon.setVisible(false);
        pnHoaDon.setVisible(false);
        pnNhanVien.setVisible(false);
        pnKhachHang.setVisible(false);
        pnUuDai.setVisible(false);
        pnDanhGia.setVisible(false);
        pnDichVu.setVisible(false);

    }//GEN-LAST:event_txtTaiKhoanMouseClicked

    private void txtBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBanMouseClicked
        pnBan.setVisible(true);
        pnTrangChu.setVisible(false);
        pnTaiKhoan.setVisible(false);
        pnThucDon.setVisible(false);
        pnHoaDon.setVisible(false);
        pnNhanVien.setVisible(false);
        pnKhachHang.setVisible(false);
        pnUuDai.setVisible(false);
        pnDanhGia.setVisible(false);
        pnDichVu.setVisible(false);

    }//GEN-LAST:event_txtBanMouseClicked

    private void txtMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMenuMouseClicked
        pnThucDon.setVisible(true);
        pnTrangChu.setVisible(false);
        pnTaiKhoan.setVisible(false);
        pnBan.setVisible(false);
        pnHoaDon.setVisible(false);
        pnNhanVien.setVisible(false);
        pnKhachHang.setVisible(false);
        pnUuDai.setVisible(false);
        pnDanhGia.setVisible(false);
        pnDichVu.setVisible(false);

    }//GEN-LAST:event_txtMenuMouseClicked

    private void txtHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoaDonMouseClicked
        pnHoaDon.setVisible(true);
        pnTrangChu.setVisible(false);
        pnBan.setVisible(false);
        pnThucDon.setVisible(false);
        pnTaiKhoan.setVisible(false);
        pnNhanVien.setVisible(false);
        pnKhachHang.setVisible(false);
        pnUuDai.setVisible(false);
        pnDanhGia.setVisible(false);
        pnDichVu.setVisible(false);

    }//GEN-LAST:event_txtHoaDonMouseClicked

    private void txtNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNhanVienMouseClicked
        pnNhanVien.setVisible(true);
        pnTrangChu.setVisible(false);
        pnBan.setVisible(false);
        pnThucDon.setVisible(false);
        pnHoaDon.setVisible(false);
        pnTaiKhoan.setVisible(false);
        pnKhachHang.setVisible(false);
        pnUuDai.setVisible(false);
        pnDanhGia.setVisible(false);
        pnDichVu.setVisible(false);

    }//GEN-LAST:event_txtNhanVienMouseClicked

    private void txtKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKhachHangMouseClicked
        pnKhachHang.setVisible(true);
        pnTrangChu.setVisible(false);
        pnBan.setVisible(false);
        pnThucDon.setVisible(false);
        pnHoaDon.setVisible(false);
        pnNhanVien.setVisible(false);
        pnTaiKhoan.setVisible(false);
        pnUuDai.setVisible(false);
        pnDanhGia.setVisible(false);
        pnDichVu.setVisible(false);

    }//GEN-LAST:event_txtKhachHangMouseClicked

    private void txtUuDaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUuDaiMouseClicked
        pnUuDai.setVisible(true);
        pnTrangChu.setVisible(false);
        pnBan.setVisible(false);
        pnThucDon.setVisible(false);
        pnHoaDon.setVisible(false);
        pnNhanVien.setVisible(false);
        pnKhachHang.setVisible(false);
        pnTaiKhoan.setVisible(false);
        pnDanhGia.setVisible(false);
        pnDichVu.setVisible(false);

    }//GEN-LAST:event_txtUuDaiMouseClicked

    private void txtDanhGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDanhGiaMouseClicked
        pnDanhGia.setVisible(true);
        pnTrangChu.setVisible(false);
        pnBan.setVisible(false);
        pnThucDon.setVisible(false);
        pnHoaDon.setVisible(false);
        pnNhanVien.setVisible(false);
        pnKhachHang.setVisible(false);
        pnUuDai.setVisible(false);
        pnTaiKhoan.setVisible(false);
        pnDichVu.setVisible(false);

    }//GEN-LAST:event_txtDanhGiaMouseClicked

    private void txtDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDichVuMouseClicked
        pnDichVu.setVisible(true);
        pnTrangChu.setVisible(false);
        pnBan.setVisible(false);
        pnThucDon.setVisible(false);
        pnHoaDon.setVisible(false);
        pnNhanVien.setVisible(false);
        pnKhachHang.setVisible(false);
        pnUuDai.setVisible(false);
        pnDanhGia.setVisible(false);
        pnTaiKhoan.setVisible(false); 

    }//GEN-LAST:event_txtDichVuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btGioiTinhNam;
    private javax.swing.JRadioButton btGioiTinhNu;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btResetNhanVien;
    private javax.swing.JButton btSuaNhanVien;
    private javax.swing.JButton btSuaTaiKhoan;
    private javax.swing.JButton btThemNhanVien;
    private javax.swing.JButton btThemTaiKhoan;
    private javax.swing.JButton btTimKiemTaiKhoan;
    private javax.swing.JButton btXoaNhanVien;
    private javax.swing.JButton btXoaTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel pnBan;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnDanhGia;
    private javax.swing.JPanel pnDichVu;
    private javax.swing.JPanel pnFormNhanVien;
    private javax.swing.JPanel pnFormTaiKhoan;
    private javax.swing.JPanel pnHoaDon;
    private javax.swing.JPanel pnKhachHang;
    private javax.swing.JPanel pnListNhanVien;
    private javax.swing.JPanel pnListTaiKhoan;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnTaiKhoan;
    private javax.swing.JPanel pnThucDon;
    private javax.swing.JPanel pnTrangChu;
    private javax.swing.JPanel pnUuDai;
    private javax.swing.JSeparator sprt2;
    private javax.swing.JSeparator sprt3;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTable tbTaiKhoan;
    private javax.swing.JLabel txtAdmin;
    private javax.swing.JLabel txtBan;
    private javax.swing.JLabel txtDangXuat;
    private javax.swing.JLabel txtDanhGia;
    private javax.swing.JTextField txtDiaChiNhanVien;
    private javax.swing.JLabel txtDichVu;
    private javax.swing.JLabel txtDoiMatKhau;
    private javax.swing.JTextField txtEmailNhanVien;
    private javax.swing.JTextField txtHoTenNhanVien;
    private javax.swing.JLabel txtHoaDon;
    private javax.swing.JLabel txtIconAd;
    private javax.swing.JLabel txtKhachHang;
    private javax.swing.JLabel txtMenu;
    private javax.swing.JTextField txtNgaySinhNhanVien;
    private javax.swing.JTextField txtNgaySinhNhanVien1;
    private javax.swing.JLabel txtNhanVien;
    private javax.swing.JTextField txtSdtNhanVien;
    private javax.swing.JLabel txtTaiKhoan;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JLabel txtTrangChu;
    private javax.swing.JLabel txtTrangThai;
    private javax.swing.JLabel txtTrangThai1;
    private javax.swing.JLabel txtUuDai;
    // End of variables declaration//GEN-END:variables
}
