/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entity.TaiKhoan;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import repository.RepositoryTaiKhoan;

/**
 *
 * @author anhha
 */
public class TrangChu extends javax.swing.JFrame {
    
    private ArrayList<TaiKhoan> listTk = new ArrayList<>();
    private DefaultTableModel dtm = new DefaultTableModel();
    private RepositoryTaiKhoan repoTk = new RepositoryTaiKhoan();
    
    /**
     * Creates new form HomePage
     */
    public TrangChu() {
        initComponents();
        listTk= repoTk.getAll();
        dtm = (DefaultTableModel) tbTaiKhoan.getModel();
        ShowTable(listTk);
    }
    
    private void ShowTable(ArrayList<TaiKhoan> list) {
        dtm.setRowCount(0);
        for (TaiKhoan tk : list) {
            dtm.addRow(new Object[]{
                tk.getMaTaiKhoan(), tk.getTenTaiKhoan(), tk.getMkTaiKhoan()
            });
        }
    }
    
   
        
    int width = 150;
    int height = 600;
    //phương thức mở menu
    public void openMenuBar(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < width; i++) {
                    pnMenu.setSize(i,height);
                    try {
                        // mở chậm
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
    //phương thức đóng menu
    public void closeMenuBar(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = width; i > 0; i--) {
                    pnMenu.setSize(i,height);
                    try {
                        // mở chậm
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        txtName = new javax.swing.JLabel();
        pnMenu = new javax.swing.JPanel();
        txtIconAd = new javax.swing.JLabel();
        sprt = new javax.swing.JSeparator();
        txtAdmin = new javax.swing.JLabel();
        txtTrangChu = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JLabel();
        txtBan = new javax.swing.JLabel();
        txtMenu = new javax.swing.JLabel();
        txtHoaDon = new javax.swing.JLabel();
        txtNhanVien = new javax.swing.JLabel();
        txtCloseMenu = new javax.swing.JLabel();
        txtNhanVien1 = new javax.swing.JLabel();
        txtNhanVien2 = new javax.swing.JLabel();
        txtNhanVien3 = new javax.swing.JLabel();
        txtNhanVien4 = new javax.swing.JLabel();
        sprt1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOpenMenu = new javax.swing.JLabel();
        pnContainer = new javax.swing.JPanel();
        pnTrangChu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnTaiKhoan = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTaiKhoan = new javax.swing.JTable();
        btThemTaiKhoan = new javax.swing.JButton();
        btSuaTaiKhoan = new javax.swing.JButton();
        btXoaTaiKhoan = new javax.swing.JButton();
        pnBan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lí");

        pnMain.setOpaque(false);
        pnMain.setPreferredSize(new java.awt.Dimension(795, 600));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 102, 0));
        txtName.setText("DOOKKI");

        pnMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu.setPreferredSize(new java.awt.Dimension(148, 600));

        txtIconAd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/administrator (1).png"))); // NOI18N

        txtAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAdmin.setText("Admin");

        txtTrangChu.setText("Trang Chủ");
        txtTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTrangChuMouseClicked(evt);
            }
        });

        txtTaiKhoan.setText("Tài Khoản");
        txtTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTaiKhoanMouseClicked(evt);
            }
        });

        txtBan.setText("Bàn");
        txtBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBanMouseClicked(evt);
            }
        });

        txtMenu.setText("Menu");

        txtHoaDon.setText("Hóa Đơn");

        txtNhanVien.setText("Nhân Viên");

        txtCloseMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        txtCloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCloseMenuMouseClicked(evt);
            }
        });

        txtNhanVien1.setText("Khách Hàng");

        txtNhanVien2.setText("Ưu Đãi");

        txtNhanVien3.setText("Đánh Giá");

        txtNhanVien4.setText("Dịch Vụ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Đổi Mật Khẩu");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Đăng Xuất");

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCloseMenu)
                    .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sprt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnMenuLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIconAd)
                                .addGroup(pnMenuLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtAdmin))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sprt1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNhanVien4)
                    .addComponent(txtNhanVien3)
                    .addComponent(txtNhanVien2)
                    .addComponent(txtNhanVien1)
                    .addComponent(txtNhanVien)
                    .addComponent(txtHoaDon)
                    .addComponent(txtMenu)
                    .addComponent(txtBan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaiKhoan)
                    .addComponent(txtTrangChu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40))
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addComponent(txtCloseMenu)
                .addGap(20, 20, 20)
                .addComponent(txtIconAd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdmin)
                .addGap(10, 10, 10)
                .addComponent(sprt, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTrangChu)
                .addGap(18, 18, 18)
                .addComponent(txtTaiKhoan)
                .addGap(18, 18, 18)
                .addComponent(txtBan)
                .addGap(18, 18, 18)
                .addComponent(txtMenu)
                .addGap(18, 18, 18)
                .addComponent(txtHoaDon)
                .addGap(18, 18, 18)
                .addComponent(txtNhanVien)
                .addGap(18, 18, 18)
                .addComponent(txtNhanVien1)
                .addGap(18, 18, 18)
                .addComponent(txtNhanVien2)
                .addGap(18, 18, 18)
                .addComponent(txtNhanVien3)
                .addGap(18, 18, 18)
                .addComponent(txtNhanVien4)
                .addGap(18, 18, 18)
                .addComponent(sprt1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        txtOpenMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu (1).png"))); // NOI18N
        txtOpenMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOpenMenuMouseClicked(evt);
            }
        });

        pnContainer.setLayout(new java.awt.CardLayout());

        jLabel9.setText("Trang chủ");

        javax.swing.GroupLayout pnTrangChuLayout = new javax.swing.GroupLayout(pnTrangChu);
        pnTrangChu.setLayout(pnTrangChuLayout);
        pnTrangChuLayout.setHorizontalGroup(
            pnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTrangChuLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel9)
                .addContainerGap(669, Short.MAX_VALUE))
        );
        pnTrangChuLayout.setVerticalGroup(
            pnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTrangChuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addContainerGap(520, Short.MAX_VALUE))
        );

        pnContainer.add(pnTrangChu, "card2");

        pnTaiKhoan.setPreferredSize(new java.awt.Dimension(794, 600));

        jLabel10.setText("Tài khoản");

        tbTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tài Khoản", "Tên Tài Khoản", "MK Tài Khoản"
            }
        ));
        tbTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTaiKhoan);

        btThemTaiKhoan.setText("Thêm");

        btSuaTaiKhoan.setText("Sửa");

        btXoaTaiKhoan.setText("Xóa");

        javax.swing.GroupLayout pnTaiKhoanLayout = new javax.swing.GroupLayout(pnTaiKhoan);
        pnTaiKhoan.setLayout(pnTaiKhoanLayout);
        pnTaiKhoanLayout.setHorizontalGroup(
            pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                .addGroup(pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btThemTaiKhoan)
                            .addComponent(btSuaTaiKhoan)
                            .addComponent(btXoaTaiKhoan)))
                    .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        pnTaiKhoanLayout.setVerticalGroup(
            pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                .addGroup(pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btThemTaiKhoan)
                        .addGap(27, 27, 27)
                        .addComponent(btSuaTaiKhoan)
                        .addGap(24, 24, 24)
                        .addComponent(btXoaTaiKhoan))
                    .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pnContainer.add(pnTaiKhoan, "card3");

        pnBan.setPreferredSize(new java.awt.Dimension(794, 600));

        jLabel1.setText("Bàn");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        jButton8.setText("jButton8");

        jButton9.setText("jButton9");

        jButton10.setText("jButton10");

        jButton11.setText("jButton11");

        jButton12.setText("jButton12");

        jButton13.setText("jButton13");

        jButton14.setText("jButton14");

        jButton15.setText("jButton15");

        jButton16.setText("jButton16");

        javax.swing.GroupLayout pnBanLayout = new javax.swing.GroupLayout(pnBan);
        pnBan.setLayout(pnBanLayout);
        pnBanLayout.setHorizontalGroup(
            pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBanLayout.createSequentialGroup()
                .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBanLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7)
                            .addComponent(jButton4))
                        .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnBanLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jButton5))
                            .addGroup(pnBanLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton14)
                                    .addComponent(jButton8)))))
                    .addGroup(pnBanLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton13)
                            .addComponent(jButton16))))
                .addGap(142, 142, 142)
                .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBanLayout.createSequentialGroup()
                        .addComponent(jButton15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnBanLayout.createSequentialGroup()
                        .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12)
                            .addComponent(jButton11)
                            .addComponent(jButton10))
                        .addGap(77, 77, 77))))
        );
        pnBanLayout.setVerticalGroup(
            pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBanLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)))
                    .addGroup(pnBanLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton10)
                        .addGap(16, 16, 16)
                        .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton11))))
                .addGap(28, 28, 28)
                .addComponent(jButton12)
                .addGap(5, 5, 5)
                .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(69, 69, 69)
                .addGroup(pnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addGap(49, 49, 49)
                .addComponent(jButton16)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pnContainer.add(pnBan, "card4");

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtOpenMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName)
                        .addContainerGap())))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName)
                    .addComponent(txtOpenMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtOpenMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOpenMenuMouseClicked
        openMenuBar();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpenMenuMouseClicked

    private void txtCloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCloseMenuMouseClicked
        closeMenuBar();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCloseMenuMouseClicked

    private void txtTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTaiKhoanMouseClicked
        pnTaiKhoan.setVisible(true);
        pnTrangChu.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaiKhoanMouseClicked

    private void txtBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBanMouseClicked
        pnBan.setVisible(true);
        pnTrangChu.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanMouseClicked

    private void txtTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTrangChuMouseClicked
        pnTrangChu.setVisible(true);
        pnTaiKhoan.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrangChuMouseClicked

    private void tbTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTaiKhoanMouseClicked
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTaiKhoanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSuaTaiKhoan;
    private javax.swing.JButton btThemTaiKhoan;
    private javax.swing.JButton btXoaTaiKhoan;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnBan;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnTaiKhoan;
    private javax.swing.JPanel pnTrangChu;
    private javax.swing.JSeparator sprt;
    private javax.swing.JSeparator sprt1;
    private javax.swing.JTable tbTaiKhoan;
    private javax.swing.JLabel txtAdmin;
    private javax.swing.JLabel txtBan;
    private javax.swing.JLabel txtCloseMenu;
    private javax.swing.JLabel txtHoaDon;
    private javax.swing.JLabel txtIconAd;
    private javax.swing.JLabel txtMenu;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtNhanVien;
    private javax.swing.JLabel txtNhanVien1;
    private javax.swing.JLabel txtNhanVien2;
    private javax.swing.JLabel txtNhanVien3;
    private javax.swing.JLabel txtNhanVien4;
    private javax.swing.JLabel txtOpenMenu;
    private javax.swing.JLabel txtTaiKhoan;
    private javax.swing.JLabel txtTrangChu;
    // End of variables declaration//GEN-END:variables
}
